"""Parser for wg-quick style ``*.conf`` files.

Mirrors ``wg-quick``'s own reading rules (``src/wg-quick/linux.bash``):
``stripped="${line%%\\#*}"``, case-insensitive keys, and *no* shell evaluation of
values. Anything the panel does not understand is kept verbatim so a rewrite
never silently drops it.
"""

from __future__ import annotations

import os

from .model import InterfaceConfig, PeerConfig, split_list

INTERFACE_KEYS = {
    "address",
    "listenport",
    "privatekey",
    "fwmark",
    "mtu",
    "dns",
    "table",
    "saveconfig",
    "preup",
    "postup",
    "predown",
    "postdown",
}

PEER_KEYS = {
    "publickey",
    "presharedkey",
    "allowedips",
    "endpoint",
    "persistentkeepalive",
}


def interface_name_for(path: str) -> str:
    """``wg-quick`` derives the interface name from the file name."""
    base = os.path.basename(path)
    return base[:-5] if base.endswith(".conf") else base


def parse_text(text: str, *, name: str = "", path: str = "") -> InterfaceConfig:
    if not name and path:
        name = interface_name_for(path)
    cfg = InterfaceConfig(name=name, path=path)

    section: str | None = None
    peer: PeerConfig | None = None

    for raw in text.splitlines():
        raw = raw.rstrip("\r")
        line = raw.strip()

        if not line:
            # Blank lines are cosmetic and regenerated by to_text(); keeping them
            # would make serialisation grow on every round trip.
            continue

        if line.startswith("#"):
            if section == "interface":
                cfg.extra.append(line)
            elif section == "peer" and peer is not None:
                if peer.comment is None and not peer.public_key:
                    peer.comment = line.lstrip("#").strip()
                else:
                    peer.extra.append(line)
            else:
                cfg.leading.append(line)
            continue

        stripped = raw.split("#", 1)[0]
        if "=" not in stripped:
            lowered = stripped.strip().lower()
            if lowered == "[interface]":
                section, peer = "interface", None
                cfg.has_interface_section = True
            elif lowered == "[peer]":
                peer = PeerConfig()
                cfg.peers.append(peer)
                section = "peer"
            elif section == "interface":
                cfg.extra.append(raw.rstrip())
            elif section == "peer" and peer is not None:
                peer.extra.append(raw.rstrip())
            else:
                cfg.leading.append(raw.rstrip())
            continue

        key, _, value = stripped.partition("=")
        key = key.strip()
        value = value.strip()
        lowered = key.lower()

        if section == "peer" and peer is not None:
            if lowered == "publickey":
                peer.public_key = value
            elif lowered == "presharedkey":
                peer.preshared_key = value
            elif lowered == "allowedips":
                peer.allowed_ips.extend(split_list(value))
            elif lowered == "endpoint":
                peer.endpoint = value
            elif lowered == "persistentkeepalive":
                peer.persistent_keepalive = value
            else:
                peer.extra.append(raw.rstrip())
            continue

        if section == "interface":
            if lowered == "address":
                cfg.address.extend(split_list(value))
            elif lowered == "listenport":
                cfg.listen_port = value
            elif lowered == "privatekey":
                cfg.private_key = value
            elif lowered == "fwmark":
                cfg.fwmark = value
            elif lowered == "mtu":
                cfg.mtu = value
            elif lowered == "dns":
                cfg.dns.extend(split_list(value))
            elif lowered == "table":
                cfg.table = value
            elif lowered == "saveconfig":
                cfg.save_config = value
            elif lowered == "preup":
                cfg.pre_up.append(value)
            elif lowered == "postup":
                cfg.post_up.append(value)
            elif lowered == "predown":
                cfg.pre_down.append(value)
            elif lowered == "postdown":
                cfg.post_down.append(value)
            else:
                cfg.extra.append(raw.rstrip())
            continue

        # A key outside any section: preserve it as leading content.
        cfg.leading.append(raw.rstrip())

    return cfg


def parse_bytes(data: bytes, *, name: str = "", path: str = "") -> InterfaceConfig:
    return parse_text(data.decode("utf-8", errors="replace"), name=name, path=path)


def load(path: str) -> InterfaceConfig:
    with open(path, "rb") as handle:
        return parse_bytes(handle.read(), path=path)
